# Generated by Django 3.0.7 on 2020-12-04 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem_solution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solution',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problem_solution.Problem'),
        ),
        migrations.AddField(
            model_name='solution',
            name='tags',
            field=models.ManyToManyField(related_name='solutions', to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='solution',
            name='technologies',
            field=models.ManyToManyField(related_name='solutions', to='technology.Technology'),
        ),
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problem_solution.Solution'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(related_name='problems', to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='editsuggestionsolution',
            name='edit_suggestion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_suggestions_Solution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editsuggestionsolution',
            name='edit_suggestion_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_solution.Solution'),
        ),
        migrations.AddField(
            model_name='editsuggestionsolution',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='problem_solution.Problem'),
        ),
        migrations.AddField(
            model_name='editsuggestionsolution',
            name='tags',
            field=models.ManyToManyField(related_name='tags_Solution', to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='editsuggestionsolution',
            name='technologies',
            field=models.ManyToManyField(related_name='technologies_Solution', to='technology.Technology'),
        ),
        migrations.AddField(
            model_name='editsuggestionproblem',
            name='edit_suggestion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_suggestions_Problem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editsuggestionproblem',
            name='edit_suggestion_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_solution.Problem'),
        ),
        migrations.AddField(
            model_name='editsuggestionproblem',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='problem_solution.Solution'),
        ),
        migrations.AddField(
            model_name='editsuggestionproblem',
            name='tags',
            field=models.ManyToManyField(related_name='tags_Problem', to='tag.Tag'),
        ),
    ]
