"""
holds the rewards points
"""
REVIEW_CREATE = 2
REVIEW_DELETE = 2
RESOURCE_CREATE = 2
RESOURCE_DELETE = 2
EDIT_SUGGESTION_CREATE = 1
EDIT_SUGGESTION_PUBLISH = 2
EDIT_SUGGESTION_REJECT = 2
MODERATOR_USER_SCORE = 50