CREATE = 'CREATE'
UPDATE = 'UPDATE'
DELETE = 'DELETE'

VERB_CREATE = 'created'
VERB_UPDATE = 'updated'
VERB_DELETE = 'deleted'
VERB_REVIEW_NEW = 'reviewed'
VERB_REVIEW_REMOVE = 'removed review of'
VERB_EDIT_NEW = 'created new edit suggestion for '
VERB_EDIT_PUBLISH = 'published an edit suggestion for '
VERB_EDIT_REJECT = 'rejected an edit suggestion for '
VERB_EDIT_DELETE = 'deleted an edit suggestion for '

VERB_DISCUSSION_NEW = 'created new post on'
VERB_DISCUSSION_EDIT = 'edited post on '
VERB_DISCUSSION_DELETE = 'deleted post on'
VERB_DISCUSSION_INACTIVATE = 'deactivated post on'

MESSAGE_ACTOR = '{actor} {verb} <a href="{url}">{name}<a/>'