# Generated by Django 3.0.7 on 2020-08-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudyresource',
            name='summary',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='historicalstudyresource',
            name='url',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='summary',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='url',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='technology',
            name='url',
            field=models.TextField(max_length=1024),
        ),
    ]
