# Generated by Django 3.0.7 on 2020-08-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0002_auto_20200808_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='thumbs_down',
            new_name='thumbs_down_array',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='thumbs_up',
            new_name='thumbs_up_array',
        ),
    ]
