# Generated by Django 3.0.7 on 2021-01-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('study_resource', '0003_auto_20210102_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsuggestionstudyresource',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='category.Category'),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resources', to='category.Category'),
        ),
    ]
