# Generated by Django 3.0.7 on 2020-08-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0003_auto_20200808_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudyresource',
            name='experience_level',
            field=models.IntegerField(choices=[(0, 'absolute beginner'), (1, 'junior'), (2, 'middle'), (3, 'experienced')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='experience_level',
            field=models.IntegerField(choices=[(0, 'absolute beginner'), (1, 'junior'), (2, 'middle'), (3, 'experienced')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicalstudyresource',
            name='url',
            field=models.TextField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='review',
            name='study_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='study_resource.StudyResource'),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='url',
            field=models.TextField(max_length=1024, unique=True),
        ),
    ]
