# Generated by Django 3.0.7 on 2021-06-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
        ('study_resource', '0003_auto_20210327_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsuggestionstudyresource',
            name='category_concepts',
            field=models.ManyToManyField(related_name='category_concepts_StudyResource', to='concepts.CategoryConcept'),
        ),
        migrations.AddField(
            model_name='editsuggestionstudyresource',
            name='technology_concepts',
            field=models.ManyToManyField(related_name='technology_concepts_StudyResource', to='concepts.TechnologyConcept'),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='category_concepts',
            field=models.ManyToManyField(related_name='related_resources', to='concepts.CategoryConcept'),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='technology_concepts',
            field=models.ManyToManyField(related_name='related_resources', to='concepts.TechnologyConcept'),
        ),
    ]
