# Generated by Django 3.0.7 on 2021-01-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0004_auto_20210118_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
