# Generated by Django 3.0.7 on 2021-07-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0005_auto_20210612_1822'),
    ]

    operations = []
