# Generated by Django 3.0.7 on 2020-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0005_auto_20200824_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(related_name='collections', to='study_resource.Tag'),
        ),
        migrations.AddField(
            model_name='collection',
            name='technologies',
            field=models.ManyToManyField(related_name='collections', to='study_resource.Technology'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='resources',
            field=models.ManyToManyField(related_name='collections', through='study_resource.CollectionResources', to='study_resource.StudyResource'),
        ),
    ]
