# Generated by Django 3.0.7 on 2020-09-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0007_auto_20200824_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudyresource',
            name='slug',
            field=models.SlugField(default='def'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyresource',
            name='slug',
            field=models.SlugField(default='def'),
            preserve_default=False,
        ),
    ]
