# Generated by Django 3.0.7 on 2020-09-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0008_auto_20200901_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudyresource',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
