# Generated by Django 3.0.7 on 2021-10-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('study_resource', '0010_auto_20210925_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyresource',
            name='tags',
            field=models.ManyToManyField(related_name='resources', to='tag.Tag'),
        ),
    ]
