# Generated by Django 3.0.7 on 2020-09-11 06:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0010_auto_20200908_0626'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studyresource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'summary'], name='gintrgm_index', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
