# Generated by Django 3.0.7 on 2021-10-03 19:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_resource', '0011_auto_20211003_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsuggestionstudyresource',
            name='url',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='url',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.CreateModel(
            name='StudyResourceIntermediary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=256)),
                ('active', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Error'), (2, 'Saved')], db_index=True, default=0)),
                ('scraped_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
