# Generated by Django 3.0.7 on 2020-09-14 02:47

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0011_auto_20200911_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudyresource',
            name='published_by',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='published_by',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='StudyResourceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='tutorials')),
                ('study_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='study_resource.StudyResource')),
            ],
        ),
    ]
