# Generated by Django 3.0.7 on 2020-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0013_auto_20200914_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyresourceimage',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='studyresourceimage',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
