# Generated by Django 3.0.7 on 2022-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0013_auto_20211003_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsuggestionstudyresource',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='editsuggestionstudyresource',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
