# Generated by Django 3.0.7 on 2022-06-14 00:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0008_auto_20210925_1227'),
        ('category', '0007_auto_20210925_1227'),
        ('technology', '0012_auto_20210925_1227'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
        ('study_resource', '0013_auto_20211003_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalStudyResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs_up_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('thumbs_down_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Approved'), (2, 'Rejected'), (4, 'Inactive')], db_index=True, default=1)),
                ('image_file', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='tutorials')),
                ('summary', models.TextField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(choices=[(0, 'Free')], db_index=True, default=0)),
                ('media', models.IntegerField(choices=[(0, 'Article')], db_index=True, default=0)),
                ('experience_level', models.IntegerField(choices=[(0, 'Absolute Beginner'), (1, 'Junior'), (2, 'Middle'), (3, 'Experienced')], db_index=True, default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_resources', to='category.Category')),
                ('category_concepts', models.ManyToManyField(related_name='internal_related_resources', to='concepts.CategoryConcept')),
                ('tags', models.ManyToManyField(related_name='internal_resources', to='tag.Tag')),
                ('technologies', models.ManyToManyField(related_name='internal_resources', through='study_resource.StudyResourceTechnology', to='technology.Technology')),
                ('technology_concepts', models.ManyToManyField(related_name='internal_related_resources', to='concepts.TechnologyConcept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalStudyResourceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='tutorials')),
                ('image_url', models.URLField(blank=True, default='', null=True)),
                ('study_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='study_resource.InternalStudyResource')),
            ],
        ),
        migrations.AddField(
            model_name='editsuggestionstudyresourcetechnology',
            name='internal_study_resource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='study_resource.InternalStudyResource'),
        ),
        migrations.AddField(
            model_name='studyresourcetechnology',
            name='internal_study_resource',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='study_resource.InternalStudyResource'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InternalReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs_up_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('thumbs_down_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('text', models.TextField(max_length=2048)),
                ('visible', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('study_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='study_resource.InternalStudyResource')),
            ],
            options={
                'unique_together': {('author', 'study_resource')},
            },
        ),
    ]
