# Generated by Django 3.0.7 on 2022-06-14 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0014_auto_20220614_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyresourcetechnology',
            name='internal_study_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_resource.InternalStudyResource'),
        ),
        migrations.AlterField(
            model_name='studyresourcetechnology',
            name='study_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_resource.StudyResource'),
        ),
    ]
