# Generated by Django 3.0.7 on 2022-06-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0014_auto_20220618_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyresourceimage',
            name='line',
            field=models.IntegerField(default=0),
        ),
    ]
