# Generated by Django 3.0.7 on 2022-06-14 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0015_auto_20220614_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editsuggestionstudyresourcetechnology',
            name='internal_study_resource',
        ),
        migrations.RemoveField(
            model_name='internalstudyresource',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='studyresourcetechnology',
            name='internal_study_resource',
        ),
        migrations.AlterField(
            model_name='studyresourcetechnology',
            name='study_resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study_resource.StudyResource'),
            preserve_default=False,
        ),
    ]
