# Generated by Django 3.0.7 on 2022-06-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0012_auto_20210925_1227'),
        ('study_resource', '0016_auto_20220614_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsuggestionstudyresourcetechnology',
            name='internal_study_resource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='study_resource.InternalStudyResource'),
        ),
        migrations.AddField(
            model_name='internalstudyresource',
            name='technologies',
            field=models.ManyToManyField(related_name='internal_resources', through='study_resource.StudyResourceTechnology', to='technology.Technology'),
        ),
        migrations.AddField(
            model_name='studyresourcetechnology',
            name='internal_study_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_resource.InternalStudyResource'),
        ),
    ]
