# Generated by Django 3.0.7 on 2022-06-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0012_auto_20210925_1227'),
        ('study_resource', '0017_auto_20220614_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editsuggestionstudyresourcetechnology',
            name='internal_study_resource',
        ),
        migrations.RemoveField(
            model_name='studyresourcetechnology',
            name='internal_study_resource',
        ),
        migrations.CreateModel(
            name='InternalStudyResourceTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('version', models.FloatField(blank=True, max_length=128, null=True)),
                ('internal_study_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_resource.InternalStudyResource')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.Technology')),
            ],
            options={
                'unique_together': {('technology', 'internal_study_resource')},
            },
        ),
        migrations.AlterField(
            model_name='internalstudyresource',
            name='technologies',
            field=models.ManyToManyField(related_name='internal_resources', through='study_resource.InternalStudyResourceTechnology', to='technology.Technology'),
        ),
    ]
