# Generated by Django 3.0.7 on 2022-06-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resource', '0018_auto_20220614_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalstudyresourceimage',
            old_name='study_resource',
            new_name='internal_study_resource',
        ),
        migrations.RemoveField(
            model_name='internalstudyresource',
            name='summary',
        ),
        migrations.AddField(
            model_name='internalstudyresource',
            name='content',
            field=models.TextField(default='Some data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalstudyresourceimage',
            name='line',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
