# Generated by Django 3.0.7 on 2022-06-14 22:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_edit_suggestion.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0008_auto_20210925_1227'),
        ('technology', '0012_auto_20210925_1227'),
        ('category', '0007_auto_20210925_1227'),
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_resource', '0019_auto_20220615_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSuggestionInternalStudyResource',
            fields=[
                ('thumbs_up_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('thumbs_down_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('name', models.CharField(max_length=255)),
                ('image_file', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='tutorials')),
                ('content', models.TextField()),
                ('price', models.IntegerField(choices=[(0, 'Free')], db_index=True, default=0)),
                ('media', models.IntegerField(choices=[(0, 'Article')], db_index=True, default=0)),
                ('experience_level', models.IntegerField(choices=[(0, 'Absolute Beginner'), (1, 'Junior'), (2, 'Middle'), (3, 'Experienced')], db_index=True, default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edit_suggestion_date_created', models.DateTimeField(auto_now_add=True)),
                ('edit_suggestion_date_updated', models.DateTimeField(auto_now=True)),
                ('edit_suggestion_reason', models.TextField()),
                ('edit_suggestion_status', models.IntegerField(choices=[(0, 'under review'), (1, 'published'), (2, 'rejected')], db_index=True, default=0)),
                ('edit_suggestion_reject_reason', models.TextField()),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='category.Category')),
                ('category_concepts', models.ManyToManyField(related_name='category_concepts_InternalStudyResource', to='concepts.CategoryConcept')),
                ('edit_suggestion_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_suggestions_EditSuggestionInternalStudyResourceTechnology', to=settings.AUTH_USER_MODEL)),
                ('edit_suggestion_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_resource.InternalStudyResource')),
                ('tags', models.ManyToManyField(related_name='tags_InternalStudyResource', to='tag.Tag')),
            ],
            options={
                'verbose_name': 'edit suggestion internal study resource',
                'ordering': ('-edit_suggestion_date_created',),
                'get_latest_by': 'edit_suggestion_date_created',
            },
            bases=(django_edit_suggestion.models.EditSuggestionChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EditSuggestionInternalStudyResourceTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.FloatField(blank=True, max_length=128, null=True)),
                ('internal_study_resource', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='study_resource.InternalStudyResource')),
                ('study_resource', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='study_resource.EditSuggestionInternalStudyResource')),
                ('technology', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='technology.Technology')),
            ],
        ),
        migrations.AddField(
            model_name='editsuggestioninternalstudyresource',
            name='technologies',
            field=models.ManyToManyField(related_name='technologies_EditSuggestionInternalStudyResourceTechnology', through='study_resource.EditSuggestionInternalStudyResourceTechnology', to='technology.Technology'),
        ),
        migrations.AddField(
            model_name='editsuggestioninternalstudyresource',
            name='technology_concepts',
            field=models.ManyToManyField(related_name='technology_concepts_InternalStudyResource', to='concepts.TechnologyConcept'),
        ),
    ]
