# Generated by Django 3.0.7 on 2022-01-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', 'create_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
