# Generated by Django 3.0.7 on 2021-06-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210612_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
