# Generated by Django 3.0.7 on 2020-06-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(choices=[('ro', 'Romanian'), ('en', 'English'), ('au', 'Australian')], default='ro', max_length=3)),
            ],
        ),
    ]
