# Generated by Django 3.0.7 on 2021-05-18 13:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0004_auto_20210426_1505'),
        ('category', '0003_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs_up_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('thumbs_down_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('experience_level', models.IntegerField(choices=[(0, 'Absolute Beginner'), (1, 'Junior'), (2, 'Middle'), (3, 'Experienced')], db_index=True, default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='category.Category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='concepts.CategoryConcept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologyConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs_up_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('thumbs_down_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('experience_level', models.IntegerField(choices=[(0, 'Absolute Beginner'), (1, 'Junior'), (2, 'Middle'), (3, 'Experienced')], db_index=True, default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology_concepts', to='concepts.CategoryConcept')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='technology.Technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
