# Generated by Django 3.0.7 on 2021-05-19 08:42

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_edit_suggestion.models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0005_technology_category_concepts'),
        ('category', '0003_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryconcept',
            name='author',
            field=models.ForeignKey(default=285, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryconcept',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technologyconcept',
            name='author',
            field=models.ForeignKey(default=285, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technologyconcept',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EditSuggestionTechnologyConcept',
            fields=[
                ('thumbs_up_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('thumbs_down_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('slug', models.SlugField(max_length=255)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('experience_level', models.IntegerField(choices=[(0, 'Absolute Beginner'), (1, 'Junior'), (2, 'Middle'), (3, 'Experienced')], db_index=True, default=0)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edit_suggestion_date_created', models.DateTimeField(auto_now_add=True)),
                ('edit_suggestion_date_updated', models.DateTimeField(auto_now=True)),
                ('edit_suggestion_reason', models.TextField()),
                ('edit_suggestion_status', models.IntegerField(choices=[(0, 'under review'), (1, 'published'), (2, 'rejected')], db_index=True, default=0)),
                ('edit_suggestion_reject_reason', models.TextField()),
                ('edit_suggestion_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_suggestions_TechnologyConcept', to=settings.AUTH_USER_MODEL)),
                ('edit_suggestion_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.TechnologyConcept')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concepts.CategoryConcept')),
                ('technology', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='technology.Technology')),
            ],
            options={
                'verbose_name': 'edit suggestion technology concept',
                'ordering': ('-edit_suggestion_date_created',),
                'get_latest_by': 'edit_suggestion_date_created',
            },
            bases=(django_edit_suggestion.models.EditSuggestionChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EditSuggestionCategoryConcept',
            fields=[
                ('thumbs_up_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('thumbs_down_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('slug', models.SlugField(max_length=255)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('experience_level', models.IntegerField(choices=[(0, 'Absolute Beginner'), (1, 'Junior'), (2, 'Middle'), (3, 'Experienced')], db_index=True, default=0)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edit_suggestion_date_created', models.DateTimeField(auto_now_add=True)),
                ('edit_suggestion_date_updated', models.DateTimeField(auto_now=True)),
                ('edit_suggestion_reason', models.TextField()),
                ('edit_suggestion_status', models.IntegerField(choices=[(0, 'under review'), (1, 'published'), (2, 'rejected')], db_index=True, default=0)),
                ('edit_suggestion_reject_reason', models.TextField()),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='category.Category')),
                ('edit_suggestion_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_suggestions_CategoryConcept', to=settings.AUTH_USER_MODEL)),
                ('edit_suggestion_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.CategoryConcept')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concepts.CategoryConcept')),
            ],
            options={
                'verbose_name': 'edit suggestion category concept',
                'ordering': ('-edit_suggestion_date_created',),
                'get_latest_by': 'edit_suggestion_date_created',
            },
            bases=(django_edit_suggestion.models.EditSuggestionChanges, models.Model),
        ),
    ]
