# Generated by Django 3.0.7 on 2021-05-21 06:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20210519_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryconcept',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editsuggestioncategoryconcept',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editsuggestiontechnologyconcept',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technologyconcept',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
