# Generated by Django 3.0.7 on 2021-06-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20210612_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryconcept',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editsuggestioncategoryconcept',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editsuggestiontechnologyconcept',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technologyconcept',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryconcept',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='editsuggestioncategoryconcept',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='editsuggestiontechnologyconcept',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='technologyconcept',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
