# Generated by Django 3.0.7 on 2021-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_auto_20210614_1053'),
    ]

    operations = []
