# Generated by Django 3.0.7 on 2021-07-02 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0004_auto_20210702_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryconcept',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='categoryconcept',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='technologyconcept',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='technologyconcept',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
