# Generated by Django 3.0.7 on 2021-09-25 12:27

from django.db import migrations, models


def set_status(apps, schema_editor):
    model_concept = apps.get_model('concepts.categoryconcept')
    model_tech = apps.get_model('concepts.technologyconcept')
    model_concept.objects.update(status=1)
    model_tech.objects.update(status=1)


class Migration(migrations.Migration):
    dependencies = [
        ('concepts', '0007_auto_20210703_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryconcept',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Approved'), (2, 'Rejected'), (4, 'Inactive')],
                                      db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='technologyconcept',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Approved'), (2, 'Rejected'), (4, 'Inactive')],
                                      db_index=True, default=1),
        ),
        migrations.RunPython(set_status, migrations.RunPython.noop)
    ]
