# Generated by Django 3.0.7 on 2021-07-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20210706_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcehistorymodel',
            name='edit_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcehistorymodel',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
