# Generated by Django 3.0.7 on 2021-07-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20210706_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcehistorymodel',
            name='operation_source',
            field=models.IntegerField(choices=[(0, 'direct'), (1, 'edit_suggestion'), (2, 'automatic')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='resourcehistorymodel',
            name='operation_type',
            field=models.IntegerField(choices=[(0, 'create'), (1, 'update'), (2, 'delete')], db_index=True, default=0),
        ),
    ]
