# Generated by Django 3.0.7 on 2022-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20210712_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcehistorymodel',
            name='operation_type',
            field=models.IntegerField(choices=[(0, 'CREATE'), (1, 'UPDATE'), (2, 'DELETE')], db_index=True, default=0),
        ),
    ]
