# Generated by Django 3.0.7 on 2021-02-04 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_resource', '0001_initial'),
        ('study_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionresources',
            name='study_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_resource.StudyResource'),
        ),
    ]
