# Generated by Django 3.0.7 on 2021-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_collection', '0003_auto_20210327_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
