# Generated by Django 3.0.7 on 2021-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_collection', '0004_auto_20210612_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Approved'), (2, 'Rejected'), (4, 'Inactive')], db_index=True, default=0),
        ),
    ]
