# Generated by Django 3.0.7 on 2020-09-29 05:15

from django.db import migrations, models
import tsvector_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('version', models.CharField(blank=True, max_length=128, null=True)),
                ('license', models.IntegerField(choices=[(0, 'public domain'), (1, 'permissive license'), (2, 'copyleft'), (3, 'noncommercial'), (4, 'proprietary'), (5, 'trade secret')], db_index=True, default=0)),
                ('url', models.TextField(max_length=1024)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('pros', models.TextField(max_length=1024)),
                ('cons', models.TextField(max_length=1024)),
                ('limitations', models.TextField(max_length=1024)),
                ('search_vector_index', tsvector_field.SearchVectorField(columns=[tsvector_field.WeightedColumn('name', 'A'), tsvector_field.WeightedColumn('description', 'B')], language='english')),
                ('ecosystem', models.ManyToManyField(related_name='related_technologies', to='technology.Technology')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
    ]
