# Generated by Django 3.0.7 on 2020-12-12 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technology',
            name='ecosystem',
            field=models.ManyToManyField(related_name='related_technologies', to='technology.Technology'),
        ),
        migrations.AddField(
            model_name='editsuggestiontechnology',
            name='ecosystem',
            field=models.ManyToManyField(related_name='ecosystem_Technology', to='technology.Technology'),
        ),
        migrations.AddField(
            model_name='editsuggestiontechnology',
            name='edit_suggestion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_suggestions_Technology', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editsuggestiontechnology',
            name='edit_suggestion_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.Technology'),
        ),
    ]
