# Generated by Django 3.0.7 on 2021-04-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210426_1412'),
        ('technology', '0002_auto_20210327_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editsuggestiontechnology',
            name='category',
        ),
        migrations.AddField(
            model_name='editsuggestiontechnology',
            name='category',
            field=models.ManyToManyField(related_name='category_Technology', to='technology.Technology'),
        ),
        migrations.RemoveField(
            model_name='technology',
            name='category',
        ),
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.ManyToManyField(related_name='related_technologies', to='category.Category'),
        ),
    ]
