# Generated by Django 3.0.7 on 2021-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210426_1412'),
        ('technology', '0003_auto_20210426_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsuggestiontechnology',
            name='category',
            field=models.ManyToManyField(related_name='category_Technology', to='category.Category'),
        ),
    ]
