# Generated by Django 3.0.7 on 2021-05-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
        ('technology', '0004_auto_20210426_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category_concepts',
            field=models.ManyToManyField(related_name='related_technologies', to='concepts.CategoryConcept'),
        ),
    ]
