# Generated by Django 3.0.7 on 2021-06-06 17:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
        ('technology', '0005_technology_category_concepts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editsuggestiontechnology',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='editsuggestiontechnology',
            name='limitations',
        ),
        migrations.RemoveField(
            model_name='editsuggestiontechnology',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='limitations',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='pros',
        ),
        migrations.AddField(
            model_name='editsuggestiontechnology',
            name='category_concepts',
            field=models.ManyToManyField(related_name='category_concepts_Technology', to='concepts.CategoryConcept'),
        ),
        migrations.AddField(
            model_name='editsuggestiontechnology',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
