# Generated by Django 3.0.7 on 2021-06-10 10:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0006_auto_20210606_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsuggestiontechnology',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
