# Generated by Django 3.0.7 on 2021-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0007_auto_20210610_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsuggestiontechnology',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editsuggestiontechnology',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
