# Generated by Django 3.0.7 on 2021-09-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0010_remove_editsuggestiontechnology_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsuggestiontechnology',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='technology',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
