# Generated by Django 3.0.7 on 2022-06-24 21:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technology', '0012_auto_20210925_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs_up_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('thumbs_down_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Approved'), (2, 'Rejected'), (4, 'Inactive')], db_index=True, default=1)),
                ('attribute_type', models.IntegerField(choices=[(0, 'pros'), (1, 'cons'), (2, 'lim'), (3, 'gf'), (4, 'ngf')], db_index=True, default=0)),
                ('content', models.TextField(max_length=256)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_attributes', to='technology.Technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
